global:
  evaluation_interval: 1m
  scrape_interval: {{ prometheus_scrape_interval }}
  scrape_timeout: 10s

rule_files:
  - /etc/config/rules
  - /etc/config/alerts

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

{% for job in prometheus_jobs %}
  - job_name: {{ job.name }}
    metrics_path: {{ job.metrics_path }}
    static_configs:
{% if job.targets.ansible_group_name is defined %}
{% for host in groups[job.targets.ansible_group_name] %}
      - targets:
        - {{ hostvars[host]['ansible_default_ipv4']['address'] }}:{{ job.targets.port }}
{% endfor %}
{% else %}
{% for target in job.targets %}
      - targets:
        - {{ target.host }}:{{ target.port }}
{% endfor %}
{% endif %}
{% endfor %}

{% if alertmanagers_group_name is defined %}
alerting:
  alertmanagers:
    - static_configs:
      - targets:
{% for host in groups[alertmanagers_group_name] %}
        - {{ hostvars[host]['alertmanager_advertise_address'] }}:{{ alertmanager_cluster_port }}
{% endfor %}
{% endif %}
