global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s

rule_files:
  - /etc/config/rules
  - /etc/config/alerts

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

{% for job in k8s_prometheus_jobs %}
  - job_name: {{ job.name }}
    metrics_path: {{ job.metrics_path }}
    static_configs:
      - targets:
{% for target in job.targets %}
        - {{ target.host }}:{{ target.port }}
{% endfor %}
{% endfor %}
