prometheus_supervisor: runit
# prometheus_supervisor: systemd

# Allow pre-release (beta) versions
prometheus_pre_release: yes

# TODO: Reinstall if there's a new version
# prometheus_latest: yes

# can be no (false) or version
prometheus_specific_release_tag_name: no

# will deploy to {{ prometheus_base_dir}}/{{ prometheus_dir }}
prometheus_base_dir: /opt
prometheus_dir: prometheus

prometheus_user: prometheus
prometheus_data_dir: /var/lib/prometheus


prometheus_alertmanager_url: http://127.0.0.1:9093

prometheus_storage_local_retention: 360h0m0s

prometheus_conf_template_name: prometheus_default.yml

prometheus_no_conf: no
